### PR TITLE
SynchronizedObservableCollection<T>.Insert(int, T) ArgumentOurOfRangeException fix

### PR DESCRIPTION
**Pull request by fjch1997**

### CODE REVIEW

**Comment by CoryCharlton** [comment]
@fjch1997 can you provide more details on the issue you are trying to solve? If possible an example to reproduce would also be helpful. 

Unless I'm missing something the change you submitted simply moves the code from the `CheckIndex(int index)` method inline to 'Insert(int index, T item)' so I'm not sure how the behavior would be different.

**Comment by fjch1997** [comment]
Sure. I thought it was too obvious (guess it's just to me) that I didn't take the time to explain anything.

Let's say you do this.

``` C#
var collection = SynchronizedObservableCollection<string>();
//collection.Count is 0.
//Then try this.
collection.Insert(0, "blah");//ArgumentOutOfRangeException is raised.
```

CheckIndex(int) then do an evaluation of (index < 0 || index >= _items.Count)
In the above case (Count == 0). This is true. and CheckIndex(int) raises an ArgumentOutOfRangeException.

By changing 

``` C#
(index < 0 || index >= _items.Count) 
```

to 

``` C#
(index < 0 || index > _items.Count)
```

(Notice the removed "=")

The exception is no longer raised when trying to append an object to the end of the collection. This is the correct behavor of ICollection<T>.Insert(int, T)

**Comment by fjch1997** [comment]
Thanks again for writing this excellent SynchronizedObservableCollection.
I was using the ConcurrentObservableCollection from Swordfish.NET.Collections (which is the #1 google search result)
But it didn't working very well. It's fine when we do the debugging and testing. But our clients are reporting some strange behaviors and crashes. We looked into it's source code but found that it's just over-complicated and that makes it error prone.

**Comment by CoryCharlton** [comment]
Makes perfect sense. At first glance I didn't notice the removed "=" but looking at the source for both `Collection<T>` and `ObservableCollection<T>` I have confirmed this is the correct behavior and I'm not sure how I introduced this issue since most of the code was copied from the original.

Glad to hear the SynchronizedObservableCollection has been useful to you :)

**Pull request merged**
